server:

  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 1s
    threads:
      max: 200
      min-spare: 10
  error:
    include-message: always

spring:
  datasource:
    username: postgres
    password: Trap.4311
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
polar:
  greeting: Welcome to the local book catalog
