server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 1s
    threads:
      max: 200
      min-spare: 10
  error:
    include-message: always
spring:
  application:
    name: "Book Service"

